services:
    slam-python:
        image: slam
        container_name: slam
        tty: true
        #network_mode: host
        devices:
            -   dev/dri/
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=/tmp/.docker.xauth
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - /home/Kitti:/home/Kitti
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
            - ./slam:/home/stereo_ptam
            #- ./localization:/catkin_ws/src
        #command: /bin/bash -c "source /.bashrc"
#        command: /bin/bash -c "code /directory-to-open --user-data-dir='.' --no-sandbox"
#       python /home/stereo_ptam/sptam.py --dataset kitti --path /home/Kitti/dataset/sequences/00
